# This is the configuration used to check the rubocop source code.

inherit_from: rubocop-todo.yml

AllCops:
  Includes:
    - Rakefile
    - Gemfile
    - Guardfile
    - config.ru
    - ruby-dmm.gemspec
  Excludes:
    - db/**
    - config/**
    - script/**
    - gems/**
    - vendor/**
