Style/HashSyntax:
  EnforcedStyle: hash_rockets

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    reduce: 'inject'

inherit_from: .rubocop_todo.yml
